"""test running migrations

Revision ID: 8590a9335fab
Revises: 4f2de3f7ddcf
Create Date: 2024-01-18 02:33:21.082324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8590a9335fab'
down_revision: Union[str, None] = '4f2de3f7ddcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
